#!/usr/bin/python

try:
	"a"+1

except Exception as e:
	print (e)
